// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrR_ZEdSVjBFI5qykk7PXhMuFvGR5Gp8',
    appId: '1:1060470892593:web:170efe9aed71f7c2380d10',
    messagingSenderId: '1060470892593',
    projectId: 'booker-context',
    authDomain: 'booker-context.firebaseapp.com',
    storageBucket: 'booker-context.appspot.com',
    measurementId: 'G-XFTLM9MDHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkC7dgRGTcj0dNWc3aIqJ8PEPEoYYcqtw',
    appId: '1:1060470892593:android:25c7b935bb8fa2e7380d10',
    messagingSenderId: '1060470892593',
    projectId: 'booker-context',
    storageBucket: 'booker-context.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOLmtnIc4XnBXva7YcH9z1PYcWhti6Tc',
    appId: '1:1060470892593:ios:075dd0300e1493c9380d10',
    messagingSenderId: '1060470892593',
    projectId: 'booker-context',
    storageBucket: 'booker-context.appspot.com',
    iosBundleId: 'com.example.booker',
  );
}
